### ISSUE TITLE
Adding a syndicus to a building doesn't work

### ISSUE THREAD

**Issue by JasperJanin** [SELab-2/Dr-Trottoir-2#369] opened 2023-05-21 15:01 UTC
example on http://localhost:3000/beheer/data_toevoegen/gebouwen/2

1. select someone as syndicus
2. press "opslaan"

Request doesn't go through

**Comment by JasperJanin** [comment] 2023-05-21 15:06
I'm investigating this while making the syndici page

**Comment by milachae** [comment] 2023-05-21 15:27
Duplicate of #361, This is already being fixed there.

**Closed** 2023-05-21 15:33 UTC
Labels: bug, duplicate, frontend
